import type { AdminItemCategory, PublicAdminItem } from "./types";

export type DefaultAdminItem = Omit<
  PublicAdminItem,
  "_id" | "createdAt" | "updatedAt"
>;

const defaultImage = "/images/destinations/hero-bg.jpg";

export const defaultAdminItems: DefaultAdminItem[] = [
  {
    category: "domestic",
    img: "/images/destinations/udaipur.jpg",
    alt: "Royal palace architecture in Rajasthan",
    badge: "Rajasthan",
    title: "Udaipur",
    text: "Royal lake views, palace hotels, heritage dining and romantic sunset experiences.",
    isActive: true,
  },
  {
    category: "domestic",
    img: "/images/destinations/goa.jpg",
    alt: "Palm-lined beach in Goa",
    badge: "Beach escape",
    title: "Goa",
    text: "Premium beach resorts, vibrant dining, water activities and relaxed coastal luxury.",
    isActive: true,
  },
  {
    category: "domestic",
    img: "/images/destinations/kerala.jpg",
    alt: "Kerala backwater landscape with houseboat",
    badge: "Nature & wellness",
    title: "Kerala",
    text: "Backwater cruises, wellness retreats, tropical landscapes and slow, soulful travel.",
    isActive: true,
  },
  {
    category: "domestic",
    img: "/images/destinations/kashmir.jpg",
    alt: "Snow-covered Himalayan mountains in Kashmir",
    badge: "Himalayan retreat",
    title: "Kashmir",
    text: "Alpine scenery, houseboat stays, garden walks and unforgettable seasonal beauty.",
    isActive: true,
  },
  {
    category: "domestic",
    img: "/images/destinations/andaman.jpg",
    alt: "Clear tropical water and white beach in the Andaman Islands",
    badge: "Island holiday",
    title: "Andaman",
    text: "Clear blue water, island resorts, diving adventures and quiet beach moments.",
    isActive: true,
  },
  {
    category: "domestic",
    img: "/images/destinations/jaipur.jpg",
    alt: "Historic architecture in Jaipur",
    badge: "Heritage city",
    title: "Jaipur",
    text: "Palace hotels, colourful bazaars, cultural experiences and refined royal hospitality.",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/maldives.jpg",
    alt: "Luxury overwater villas in the Maldives",
    badge: "Indian Ocean icon",
    title: "Maldives Private-Island Escape",
    text: "Overwater villas, private pools, turquoise lagoons and intimate experiences designed for honeymoons and special celebrations.",
    cta: "Explore Maldives",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/dubai.jpg",
    alt: "Dubai skyline and luxury city hotels",
    badge: "City luxury",
    title: "Dubai",
    text: "Skyline hotels, desert experiences and world-class attractions.",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/bali.jpg",
    alt: "Tropical landscape and temple in Bali",
    badge: "Culture & wellness",
    title: "Bali",
    text: "Private villas, tropical beaches, spa retreats and timeless culture.",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/singapore.jpg",
    alt: "Singapore skyline at Marina Bay",
    badge: "Family favourite",
    title: "Singapore",
    text: "Iconic architecture, family attractions and sophisticated city stays.",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/switzerland.jpg",
    alt: "Swiss Alps and mountain lake",
    badge: "Scenic Europe",
    title: "Switzerland",
    text: "Alpine landscapes, luxury trains, lakeside towns and romantic journeys.",
    isActive: true,
  },
  {
    category: "international",
    img: "/images/destinations/mauritius.jpg",
    alt: "Tropical beachfront resort in Mauritius",
    badge: "Island elegance",
    title: "Mauritius",
    text: "Beachfront resorts, clear lagoons and relaxed island experiences.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/udaipur.jpg",
    alt: "Palace-style luxury hotel in Udaipur",
    label: "Heritage icon",
    location: "Udaipur, India",
    title: "Taj Lake Palace",
    text: "A celebrated palace hotel offering an atmospheric lake setting and royal-inspired hospitality.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/dubai.jpg",
    alt: "Luxury hotel and skyline in Dubai",
    label: "Dubai landmark",
    location: "Dubai, UAE",
    title: "Burj Al Arab",
    text: "An internationally recognised luxury address known for bold design, service and sea views.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/singapore.jpg",
    alt: "Marina Bay skyline in Singapore",
    label: "Skyline experience",
    location: "Singapore",
    title: "Marina Bay Sands",
    text: "A spectacular urban stay combining panoramic views, dining, shopping and entertainment.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/oberoi-udaivilas.jpg",
    alt: "Palatial garden hotel in Udaipur",
    label: "Royal retreat",
    location: "Udaipur, India",
    title: "The Oberoi Udaivilas",
    text: "Palatial architecture, landscaped gardens and tranquil lake-facing suites.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/switzerland.jpg",
    alt: "Alpine luxury hotel in Switzerland",
    label: "Alpine icon",
    location: "Zermatt, Switzerland",
    title: "The Omnia",
    text: "Panoramic mountain views, refined alpine design and an exclusive spa retreat.",
    isActive: true,
  },
  {
    category: "hotel",
    img: "/images/destinations/mauritius.jpg",
    alt: "Beachfront luxury hotel in Mauritius",
    label: "Island retreat",
    location: "Mauritius",
    title: "One&Only Le Saint Geran",
    text: "A private peninsula setting with white-sand beaches and elevated island hospitality.",
    isActive: true,
  },
  {
    category: "resort",
    img: "/images/destinations/maldives.jpg",
    alt: "Overwater luxury resort in the Maldives",
    label: "Private island",
    location: "Maldives",
    tag: "Honeymoon",
    title: "Soneva Jani",
    text: "Expansive overwater living, private pools and a secluded lagoon setting.",
    isActive: true,
  },
  {
    category: "resort",
    img: "/images/destinations/oberoi-udaivilas.jpg",
    alt: "Indian palace and garden architecture",
    label: "Royal retreat",
    location: "Udaipur, India",
    tag: "Luxury",
    title: "The Oberoi Udaivilas",
    text: "Palatial architecture, landscaped gardens and tranquil views across the lake.",
    isActive: true,
  },
  {
    category: "resort",
    img: "/images/destinations/atlantis-palm.jpg",
    alt: "Luxury tropical beach resort with pool",
    label: "Family favourite",
    location: "Dubai, UAE",
    tag: "Resort",
    title: "Atlantis The Palm",
    text: "A vibrant resort experience combining rooms, dining, attractions and family entertainment.",
    isActive: true,
  },
  {
    category: "package",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts holiday package",
    title: "Honeymoon Escapes",
    text: "Romantic villas, private dining, spa experiences and memorable island or mountain settings.",
    cta: "Plan a romantic holiday ->",
    isActive: true,
  },
  {
    category: "package",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts holiday package",
    title: "Family Holidays",
    text: "Comfortable stays, child-friendly attractions and balanced itineraries for every generation.",
    cta: "Plan a family holiday ->",
    isActive: true,
  },
  {
    category: "package",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts holiday package",
    title: "Luxury Escapes",
    text: "Iconic hotels, premium transfers, private experiences and personalised travel assistance.",
    cta: "Create a luxury escape ->",
    isActive: true,
  },
  {
    category: "package",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts holiday package",
    title: "Corporate Retreats",
    text: "Resort venues, group accommodation, meeting support and team-building experiences.",
    cta: "Discuss a group retreat ->",
    isActive: true,
  },
  {
    category: "membership",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts Explorer membership",
    title: "Explorer",
    text: "For travellers just getting started",
    price: "Free",
    perks: [
      "Member-only fares on select hotels",
      "Birthday travel voucher",
      "Priority customer support",
    ],
    cta: "Join Explorer",
    isActive: true,
  },
  {
    category: "membership",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts Voyager membership",
    title: "Voyager",
    text: "For frequent domestic & international travellers",
    price: "Rs 4,999/yr",
    perks: [
      "Everything in Explorer",
      "Complimentary room upgrades (subject to availability)",
      "Late checkout at partner hotels",
      "Dedicated travel concierge",
    ],
    cta: "Join Voyager",
    featured: true,
    isActive: true,
  },
  {
    category: "membership",
    img: defaultImage,
    alt: "Phoenix Hotels and Resorts Elite membership",
    title: "Elite",
    text: "For the discerning luxury traveller",
    price: "Rs 12,999/yr",
    perks: [
      "Everything in Voyager",
      "Complimentary airport transfers",
      "Exclusive access to private-island resorts",
      "Personalised itinerary planning",
      "24/7 emergency travel assistance",
    ],
    cta: "Join Elite",
    isActive: true,
  },
  {
    category: "review",
    img: defaultImage,
    alt: "Aarav Kiara review",
    title: "Aarav & Kiara",
    text: "Our Maldives holiday felt effortless. The resort recommendation matched exactly what we wanted for our honeymoon.",
    rating: 5,
    isActive: true,
  },
  {
    category: "review",
    img: defaultImage,
    alt: "Mehta Family review",
    title: "Mehta Family",
    text: "The Udaipur stay, transfers and experiences were coordinated beautifully for our family celebration.",
    rating: 5,
    isActive: true,
  },
  {
    category: "review",
    img: defaultImage,
    alt: "Riya Patel review",
    title: "Riya Patel",
    text: "Planning our corporate retreat was simple with clear package options and prompt support throughout.",
    rating: 4,
    isActive: true,
  },
  {
    category: "review",
    img: defaultImage,
    alt: "Karan Sethi review",
    title: "Karan Sethi",
    text: "Great support finding a family-friendly resort in Goa. Everything was exactly as described.",
    rating: 5,
    isActive: true,
  },
];

export function getDefaultAdminItems(category?: AdminItemCategory) {
  return category
    ? defaultAdminItems.filter((item) => item.category === category)
    : defaultAdminItems;
}
